spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    ds:
      master:
        username: root
        password: 1234
        url: jdbc:mysql:///mybatis?serverTimezone=Asia/Shanghai
      slave:
        username: root
        password: 1234
        url: jdbc:mysql://196.168.31.128:3306/doublesourse

#        自定义配置两个数据源

